name: Publish to NPM
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: publishing
    # See https://docs.npmjs.com/trusted-publishers#github-actions-configuration
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      # NPM 11.x is required for OIDC publishing
      - run: npm install -g npm@latest
      - run: corepack enable
      - run: yarn install
      - name: Run tests
        run: yarn run test
      - name: Publish
        run: yarn run publish-ci
        env:
          NPM_CONFIG_PROVENANCE: true
